language: ruby
rvm: 2.4
env:
  global: NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - bundle exec jekyll build
script:
  - bundle exec rake test
deploy:
  - provider: script
    script: bundle exec rake push:branch
    skip_cleanup: true
    on:
      branch: production
  - provider: script
    skip_cleanup: true
    script: ls -a
    on:
      branch: staging
