language: ruby
rvm: 2.4
branches:
  only: master
env:
  global: NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - bundle exec jekyll build
script:
  - bundle exec rake test
# after_success:
#   - bundle exec rake travis:deploy:s3
