language: ruby
rvm: 2.4
env:
  global: NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - bundle exec jekyll build
script:
  - bundle exec rake test
deploy:
  provider: script
  on:
    - branch: production
      script: echo "i'm on production!"
    - branch: staging
      script: echo "i'm on staging!"
