
# Site settings
title: Butler Studio
email: studio@libraries.cul.columbia.edu
description: >
  The Butler Library Studio provides a co-working space to the Columbia community for gatherings and collaborations that advance the practice of pedagogy and digital scholarship.
baseurl: ''
url: ''

exclude: [Rakefile, vendor, Gemfile*]

# Collections for happenings
collections:
  happenings:
    output: true
