# Site settings
title: CUL Studio
description: >- # this means to ignore newlines until "baseurl:"
  The Columbia University Libraries Studio is both a space and a practice that
  enables ethical, sustainable, FAIR, and collaborative, digitally-driven
  research and pedagogy.
email: studio@libraries.cul.columbia.edu
baseurl: '/dlst-studio'
image: "https://studio.cul.columbia.edu/assets/og-moth.jpg"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
kramdown:
  input: GFM
  footnote_backlink: '&#x21A9;&#xFE0E;'
  auto_id_prefix: s-
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

permalink: pretty
# Collections for happenings
collections:
  ongoing:
    output: true
  pages:
    output: true
  upcoming:
    output: true
fb:
  admins: elotroalex
  app_id: 589495744558280
defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: page

